
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (1, "Spong", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (2, "Jones", "Zoe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (3, "Vernon", "Donald");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (4, "Jones", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (5, "Fleet", "Margaret");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (6, "Partridge", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (7, "Ward", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (8, "Fleet", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (9, "Butler", "Darren");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (10, "Butler", "Ashley");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (11, "Smith", "Pat");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (12, "Ward", "Zoe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (13, "Winters", "Margaret");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (14, "Fleet", "Jack");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (15, "Timson", "Judy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (16, "Johnson", "Pat");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (17, "Davidson", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (18, "Smith", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (19, "Johnson", "Donald");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (20, "Fleet", "Trisha");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (21, "Fleet", "Zoe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (22, "Butler", "Judy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (23, "Summers", "Ashley");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (24, "Turner", "Cindy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (25, "Partridge", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (26, "Rain", "Lou");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (27, "Rain", "Judy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (28, "Vernon", "Cindy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (29, "Summers", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (30, "Turner", "Zoe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (31, "Johnson", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (32, "Turner", "Jacob");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (33, "Turner", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (34, "Johnson", "Pat");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (35, "Hill", "Jacob");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (36, "Fleet", "Brenda");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (37, "Bench", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (38, "Bench", "Susan");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (39, "Partridge", "Chris");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (40, "Turner", "Margaret");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (41, "Davidson", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (42, "Davidson", "Susan");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (43, "Rain", "Margaret");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (44, "Rain", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (45, "Smith", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (46, "Bench", "Pat");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (47, "Smith", "Lou");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (48, "Ward", "James");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (49, "Johnson", "Donald");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (50, "Fleet", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (51, "Spong", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (52, "Turner", "Jack");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (53, "Winters", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (54, "Fleet", "Cindy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (55, "Butler", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (56, "Butler", "Cindy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (57, "Davidson", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (58, "Winters", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (59, "Jones", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (60, "Winters", "Darren");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (61, "Winters", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (62, "Rain", "Jack");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (63, "Hill", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (64, "Bench", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (65, "Ash", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (66, "Smith", "Ashley");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (67, "Davidson", "James");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (68, "Fleet", "Jack");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (69, "Ash", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (70, "Turner", "Brenda");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (71, "Fleet", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (72, "Jones", "Jack");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (73, "Hill", "Margaret");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (74, "Fleet", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (75, "Bench", "Trisha");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (76, "Davidson", "Chris");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (77, "Summers", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (78, "Spong", "Chris");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (79, "Johnson", "James");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (80, "West", "Brenda");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (81, "Winters", "James");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (82, "Rain", "Jacob");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (83, "Johnson", "Jacob");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (84, "Spong", "Brenda");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (85, "Butler", "Judy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (86, "Timson", "Pat");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (87, "Davidson", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (88, "West", "Trisha");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (89, "Turner", "Margaret");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (90, "Ash", "James");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (91, "Hill", "Chris");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (92, "Rain", "Lou");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (93, "Johnson", "Jacob");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (94, "Johnson", "Trisha");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (95, "Fleet", "Zoe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (96, "Jones", "Brenda");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (97, "West", "Lou");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (98, "Davidson", "Jacob");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (99, "Johnson", "Susan");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (100, "Winters", "Cindy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (101, "Butler", "Brenda");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (102, "Partridge", "Jacob");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (103, "Timson", "Jack");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (104, "Butler", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (105, "Smith", "Zoe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (106, "Spong", "Trisha");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (107, "Turner", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (108, "Hill", "James");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (109, "Ward", "Chris");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (110, "Winters", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (111, "Ward", "Pat");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (112, "Ward", "Chris");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (113, "Butler", "Chris");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (114, "Ward", "Judy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (115, "Bench", "Susan");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (116, "Butler", "James");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (117, "Johnson", "Zoe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (118, "Hill", "Pat");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (119, "Johnson", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (120, "Butler", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (121, "Butler", "Trisha");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (122, "Rain", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (123, "Johnson", "Trisha");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (124, "Winters", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (125, "Vernon", "James");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (126, "Spong", "Chris");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (127, "Turner", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (128, "Hill", "Susan");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (129, "Ash", "Jacob");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (130, "Summers", "Lou");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (131, "Spong", "Judy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (132, "West", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (133, "Turner", "Joe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (134, "Rain", "Brenda");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (135, "Rain", "Donald");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (136, "Smith", "Brenda");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (137, "Butler", "Darren");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (138, "Bench", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (139, "Butler", "Theresa");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (140, "Jones", "Brenda");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (141, "Timson", "Cindy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (142, "West", "Darren");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (143, "Ash", "Margaret");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (144, "Turner", "Margaret");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (145, "Rain", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (146, "Timson", "Howard");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (147, "Fleet", "Zoe");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (148, "Hill", "Trisha");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (149, "Timson", "John");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (150, "Johnson", "Judy");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (151, "Ward", "Susan");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (152, "Ward", "Donald");
insert into EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (153, "Davidson", "Ashley");