
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (1, bacon);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (2, green olives);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (3, ham);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (4, parmesan);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (5, green peppers);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (6, pepperoni);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (7, pickles);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (8, buffalo sauce);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (9, sriracha);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (10, jalapenos);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (11, mushrooms);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (12, salami);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (13, onions);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (14, sausage);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (15, tomatoes);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (16, anchovies);
insert into TOPPINGS(TOPPINGS_ID, TOPPINGS_TYPE) VALUES (17, black olives);